version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s"

handlers:
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/flask_app.log
    maxBytes: 1048576
    backupCount: 3
    encoding: utf8

  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

loggers:
  flask_app:
    level: DEBUG
    handlers: [file_handler, console]
    propagate: no

root:
  level: INFO
  handlers: [file_handler]
